'use strict';const assert=require('assert');const A=require('../docs/murmur-adaptive.js');const DAY=86400000,now=Date.UTC(2026,9,3,12);let count=0;function test(name,fn){try{fn();count++;}catch(e){console.error('FAIL:',name);throw e}}
const opts={now};let seq=0;function event(o={}){return {id:'e'+(++seq),questionId:'q'+seq,partId:'a',course:'DIGI210',topic:'Boolean algebra & simplification',at:now-DAY,credit:1,status:'mastered',independent:true,...o}}
function topic(es){return A.summarize(es,opts).topics[0]}
function cat(topic='Boolean algebra & simplification',id='qnew',course='DIGI210'){return {id,partId:'a',course,topic,title:id}}
test('empty data is not mastery',()=>{assert.equal(A.summarize([],opts).totals.events,0);const r=A.recommend([],[cat()],opts);assert.equal(r[0].state,'new');assert.equal(r[0].confidence,0)});
test('one independent correct is insufficient',()=>{const t=topic([event()]);assert.equal(t.state,'insufficient-evidence');assert.equal(t.independentCorrect,1);assert(t.confidence<.2)});
test('diverse spaced answers establish observed strength',()=>{const es=Array.from({length:8},(_,i)=>event({questionId:'q'+(i%4),at:now-(4-Math.floor(i/2))*DAY}));const t=topic(es);assert.equal(t.state,'strong');assert.equal(t.independentAttempts,8);assert.equal(t.distinctItems,4);assert.equal(t.distinctDays,4)});
for(const type of ['manual','revealed','guided','selfReport','lecture','hint','unknown'])test(type+' cannot establish mastery',()=>{let ext={};if(type==='manual')ext={status:'manual'};if(type==='revealed')ext={revealed:true};if(type==='guided')ext={assisted:true};if(type==='selfReport')ext={selfReported:true};if(type==='lecture')ext={mode:'lecture-check'};if(type==='hint')ext={hintsUsed:1};if(type==='unknown')ext={independent:undefined};let t=topic(Array.from({length:20},()=>event(ext)));assert.equal(t.independentAttempts,0);assert.notEqual(t.state,'strong')});
test('same-day spam does not inflate evidence',()=>{let es=Array.from({length:100},(_,i)=>event({questionId:'same',at:now-10000+i*10}));const t=topic(es);assert.equal(t.independentAttempts,1);assert.equal(t.distinctItems,1)});
test('first failure persists despite same-day correction',()=>{const es=[event({questionId:'same',at:now-5000,credit:0,status:'missed'}),event({questionId:'same',at:now-2000})];assert.equal(topic(es).independentCorrect,0);assert.equal(topic(es).independentAttempts,1)});
test('later same-day independent miss retains accuracy but schedules repair',()=>{const es=[event({questionId:'same',at:now-5000}),event({questionId:'same',at:now-2000,credit:0,status:'missed'})],s=A.summarize(es,opts),t=s.topics[0],it=Object.values(s.items)[0];assert.equal(t.independentAttempts,1);assert.equal(t.independentCorrect,1);assert.equal(t.accuracy,1);assert.equal(t.state,'needs-work');assert.equal(t.repairsNeeded,1);assert.equal(it.dueAt,now-2000+15*60000);assert.equal(it.streak,0);assert.match(t.reason,/graded miss/)});
test('late same-day miss removes strong label without manufacturing evidence',()=>{const es=Array.from({length:8},(_,i)=>event({questionId:'q'+(i%4),at:now-(4-Math.floor(i/2))*DAY}));es.push(event({questionId:'q0',at:now-5000}));assert.equal(topic(es).state,'strong');es.push(event({questionId:'q0',at:now-1000,credit:0,status:'missed'}));const t=topic(es);assert.equal(t.state,'needs-work');assert.equal(t.independentAttempts,9);assert.equal(t.independentCorrect,9);assert.equal(t.repairsNeeded,1)});
test('same-day correction and another part do not clear outstanding repair',()=>{const es=[event({questionId:'same',at:now-5000}),event({questionId:'same',at:now-4000,credit:.5,status:'missed'}),event({questionId:'same',at:now-3000}),event({questionId:'same',partId:'b',at:now-1000})];const t=topic(es);assert.equal(t.repairsNeeded,1);assert.equal(t.state,'needs-work');assert.equal(t.independentAttempts,2);const later=[...es,event({questionId:'same',at:now+DAY})],future=A.summarize(later,{now:now+DAY});assert.equal(future.topics[0].repairsNeeded,0);assert.equal(future.items['DIGI210|same|a'].streak,1)});
test('repeated miss cannot postpone an already due repair',()=>{const es=[event({questionId:'same',at:now-3600000,credit:0,status:'missed'}),event({questionId:'same',at:now-1000,credit:0,status:'missed'})],s=A.summarize(es,opts);assert.equal(Object.values(s.items)[0].dueAt,now-3600000+15*60000);assert(s.topics[0].isDue)});
test('ungraded or self-rated outcomes cannot create independently established repair',()=>{const es=[event({questionId:'same',at:now-5000}),event({questionId:'same',at:now-1000,credit:0,status:'manual',selfReported:true})];assert.equal(topic(es).repairsNeeded,0)});
for(const status of ['incorrect','missed','wrong','failed'])test('graded assisted '+status+' schedules repair without independent credit',()=>{const e=event({questionId:'same',at:now-1000,credit:0,status,independent:false,assisted:true}),s=A.summarize([e],opts),t=s.topics[0],it=Object.values(s.items)[0];assert.equal(t.repairsNeeded,1);assert.equal(t.independentAttempts,0);assert.equal(t.state,'needs-work');assert.equal(it.dueAt,now-1000+15*60000);assert.match(t.reason,/graded miss/)});
test('guided graded mistake removes strong label while preserving independent accuracy',()=>{const es=Array.from({length:8},(_,i)=>event({questionId:'q'+(i%4),at:now-(4-Math.floor(i/2))*DAY}));assert.equal(topic(es).state,'strong');es.push(event({questionId:'q0',credit:.5,status:'incorrect',independent:false,assisted:true,at:now-1000}));const t=topic(es);assert.equal(t.state,'needs-work');assert.equal(t.independentAttempts,8);assert.equal(t.accuracy,1);assert.equal(t.repairsNeeded,1);es.push(event({questionId:'q0',assisted:true,at:now}));assert.equal(topic(es).repairsNeeded,1)});
test('support-only and ungraded zero-credit events are not graded mistakes',()=>{for(const ext of [{status:'guided',assisted:true,mode:'tutor-help'},{status:'revealed',revealed:true,assisted:true},{status:'missed',selfReported:true,assisted:true},{status:'ungraded',assisted:true},{status:'incorrect',revealed:true,assisted:true}]){const e=event({credit:0,independent:false,at:now-1000,...ext}),s=A.summarize([e],opts);assert.equal(s.topics[0].repairsNeeded,0);assert.notEqual(Object.values(s.items)[0].dueAt,now-1000+15*60000);assert.equal(s.totals.independentAttempts,0)}});
test('grading after an earlier hint still brings repair forward',()=>{const es=[event({questionId:'same',at:now-2000,credit:0,status:'guided',assisted:true,independent:false}),event({questionId:'same',at:now-1000,credit:0,status:'incorrect'})],s=A.summarize(es,opts);assert.equal(s.totals.independentAttempts,0);assert.equal(s.topics[0].repairsNeeded,1);assert.equal(Object.values(s.items)[0].dueAt,now-1000+15*60000)});
test('correct after reveal is contaminated for a day',()=>{const es=[event({questionId:'same',at:now-3600000,revealed:true,independent:false}),event({questionId:'same',at:now-1000})];assert.equal(topic(es).independentAttempts,0);assert.equal(topic(es).guided,1)});
test('same-millisecond help conservatively precedes an independent success',()=>{const help=event({id:'z-help',questionId:'same',at:now-1000,credit:0,status:'guided',assisted:true,independent:false}),answer=event({id:'a-answer',questionId:'same',at:now-1000});const t=topic([answer,help]);assert.equal(t.independentAttempts,0);assert.equal(t.guided,2)});
test('feedback at same timestamp preserves the preceding graded error',()=>{const miss=event({id:'z-miss',questionId:'same',at:now-5000,credit:0,status:'missed'}),feedback=event({id:'a-feedback',questionId:'same',at:now-5000,credit:0,status:'revealed',revealed:true,independent:false,mode:'answer-feedback'}),later=event({questionId:'same',at:now-1000});const t=topic([feedback,later,miss]);assert.equal(t.independentAttempts,1);assert.equal(t.independentCorrect,0);assert.equal(t.revealed,1);assert.equal(t.guided,1)});
test('fresh answer after assistance delay counts',()=>{const es=[event({questionId:'same',at:now-2*DAY,revealed:true}),event({questionId:'same',at:now-1000})];assert.equal(topic(es).independentAttempts,1)});
test('duplicates and permutations are deterministic',()=>{let es=Array.from({length:15},(_,i)=>event({at:now-i*DAY}));assert.deepEqual(A.summarize(es,opts),A.summarize(es.slice().reverse().concat(es),opts))});
test('higher correction revision wins',()=>{const x=event({id:'same'}),y={...x,revision:1,credit:0,status:'missed'};assert.equal(topic([y,x]).independentCorrect,0);assert.equal(topic([x,y]).independentAttempts,1)});
test('newer updatedAt wins tied revisions',()=>{const x=event({id:'same',updatedAt:now-5}),y={...x,updatedAt:now,credit:0};assert.equal(topic([x,y]).independentCorrect,0)});
test('invalid events are excluded',()=>{const r=A.summarize([null,event({at:'bad'}),event({at:now+DAY}),event({course:''}),event({questionId:''}),event({credit:NaN})],opts);assert.equal(r.totals.ignored,5);assert.equal(r.totals.independentAttempts,0)});
test('partial credit is not full correct',()=>{const t=topic([event({credit:.5})]);assert.equal(t.independentCorrect,0);assert.equal(t.recentAccuracy,.5)});
test('errors reflect actual tags on missed independent answers',()=>{const t=topic([event({credit:0,status:'missed',tags:['bar scope','bar scope']}),event({credit:0,status:'missed',tags:['bar scope']}),event({tags:['not an error']})]);assert.deepEqual(t.errors,[{tag:'bar scope',count:2}]);assert.equal(t.state,'needs-work')});
test('course isolation and safe topic keys',()=>{let es=[event({course:'__proto__',topic:'constructor'}),event({course:'ELTR238'})];let s=A.summarize(es,opts);assert.equal(s.topics.length,2);assert.equal(s.byTopic['__proto__|constructor'].independentAttempts,1)});
test('aliases join matching digital concepts only',()=>{let es=[event({topic:'Karnaugh maps'}),event({topic:'Boolean algebra & simplification'})];assert.equal(A.summarize(es,opts).topics.length,1);assert.equal(A.canonicalTopic('OTHER','Karnaugh maps'),'Karnaugh maps')});
test('explicit aliases work',()=>{assert.equal(A.canonicalTopic('C','old',{'C|old':'new'}),'new')});
test('spacing begins one day after first independent success',()=>{let e=event({at:now});let it=Object.values(A.summarize([e],opts).items)[0];assert.equal(it.dueAt,now+DAY)});
test('separate days expand intervals and failure resets',()=>{const es=[event({questionId:'q',at:now-7*DAY}),event({questionId:'q',at:now-3*DAY}),event({questionId:'q',at:now})];assert.equal(Object.values(A.summarize(es,opts).items)[0].dueAt,now+7*DAY);es.push(event({questionId:'q',at:now+DAY,credit:0,status:'missed'}));assert.equal(Object.values(A.summarize(es,{now:now+DAY}).items)[0].dueAt,now+DAY+15*60000)});
test('manual ratings never postpone a due review',()=>{const es=[event({questionId:'q',at:now-5*DAY}),event({questionId:'q',at:now,selfReported:true})];assert.equal(Object.values(A.summarize(es,opts).items)[0].dueAt,now-4*DAY)});
test('recommendations return distinct available items',()=>{const cats=[cat('One','q1'),cat('One','q1'),{...cat('One','q2'),available:false},{...cat('One','q3'),unlock:'2029-01-01'},cat('Two','q4')];let r=A.recommend([],cats,{now,limit:10});assert.deepEqual(r.map(x=>x.questionId).sort(),['q1','q4']);assert.equal(A.recommend([],cats,{now,limit:0}).length,0)});
test('recent question gets cooldown with alternative',()=>{const es=[event({questionId:'q1',topic:'One',at:now})];const r=A.recommend(es,[cat('One','q1'),cat('One','q2')],opts);assert.equal(r[0].questionId,'q2')});
test('weak prerequisite is preferred, not a hard lock',()=>{const cats=[cat('Boolean algebra & simplification','advanced'),cat('Logic gates, truth tables & timing','foundation')];const r=A.recommend([],cats,opts);assert.equal(r[0].questionId,'foundation');assert(r[0].reason.includes('before'));assert(r.some(x=>x.questionId==='advanced'))});
test('cyclic prerequisites terminate',()=>{const cats=[{...cat('T1','one'),prerequisites:['T2']},{...cat('T2','two'),prerequisites:['T1']}];assert.equal(A.recommend([],cats,opts).length,2)});
test('interleaving spans topics and reserves exploration',()=>{let es=[];let cats=[];for(let k=0;k<5;k++){for(let i=0;i<3;i++)es.push(event({topic:'Weak'+k,credit:0,status:'missed',at:now-i*DAY}));for(let i=0;i<3;i++)cats.push(cat('Weak'+k,'w'+k+'-'+i))}cats.push(cat('New','explore'));let r=A.recommend(es,cats,{now,limit:4});assert(r.some(x=>x.questionId==='explore'));assert(new Set(r.map(x=>x.topic)).size>=3)});
test('course filter confines recommendations',()=>{assert(A.recommend([],[cat('T','a','DIGI210'),cat('T','b','MATH237')],{now,course:'MATH237'}).every(r=>r.course==='MATH237'))});
test('inputs are never mutated',()=>{const es=[event()],cats=[cat()];const original=JSON.stringify([es,cats]);A.summarize(es,opts);A.recommend(es,cats,opts);assert.equal(JSON.stringify([es,cats]),original)});
// Repeatable fuzz checks: arbitrary evidence order, assistance flags, duplicate revisions, mixed courses.
let seed=904;const rnd=()=>((seed=Math.imul(seed,1664525)+1013904223>>>0)/2**32);for(let k=0;k<300;k++)test('seeded invariants '+k,()=>{const es=Array.from({length:50},(_,i)=>event({questionId:'q'+Math.floor(rnd()*8),topic:'T'+Math.floor(rnd()*3),course:rnd()<.5?'DIGI210':'MATH237',at:now-Math.floor(rnd()*20)*DAY,credit:rnd()<.6?1:0,assisted:rnd()<.2,revealed:rnd()<.1,selfReported:rnd()<.1}));let a=A.summarize(es,opts),b=A.summarize(es.slice().reverse(),opts);assert.deepEqual(a,b);for(const t of a.topics){assert(t.independentCorrect<=t.independentAttempts);assert(t.confidence>=0&&t.confidence<=1);if(t.state==='strong'){assert(t.independentAttempts>=6);assert(t.distinctItems>=3);assert(t.distinctDays>=2)}}let r=A.recommend(es,[cat('T0','n0'),cat('T1','n1'),cat('T2','n2')],opts);assert.equal(new Set(r.map(x=>x.itemKey)).size,r.length);assert(r.every(x=>Number.isFinite(x.priority)&&x.reason.length))});
test('deleted evidence is ignored',()=>{assert.equal(A.summarize([event({deleted:true})],opts).totals.events,0)});
 test('invalid credits do not establish mastery',()=>{for(const credit of [100,-1,'1',true])assert.equal(topic([event({credit})]).independentAttempts,0)});
 test('subparts of one question do not establish varied mastery',()=>{const es=Array.from({length:10},(_,i)=>event({questionId:'one',partId:String(i%5),at:now-Math.floor(i/5)*DAY}));const t=topic(es);assert.equal(t.distinctItems,1);assert.notEqual(t.state,'strong')});
 test('crossing midnight cannot produce spaced mastery in minutes',()=>{const midnight=Date.UTC(2026,9,3),es=Array.from({length:6},(_,i)=>event({questionId:'q'+(i%3),at:midnight+(i<3?-60000:60000)}));assert.notEqual(topic(es).state,'strong')});
 console.log(count+' adaptive tests passed');
