const fs=require('node:fs'),vm=require('node:vm'),assert=require('node:assert/strict'),path=require('node:path');
const app=fs.readFileSync(path.join(__dirname,'../docs/app.js'),'utf8');const code=app.slice(app.indexOf('let paidConfirmationPending'),app.indexOf("function renderKeys(message"))+'\nthis.confirmPaidAction=confirmPaidAction;';
function boot(){const ids=['paidConfirmDialog','paidConfirmYes','paidConfirmNo','paidConfirmTitle','paidConfirmMessage'];const nodes=Object.fromEntries(ids.map(id=>[id,{textContent:'',open:false,focus(){this.focused=true;},showModal(){this.open=true;},close(){this.open=false;this.onclose?.();},removeAttribute(){},setAttribute(){}}]));const c=vm.createContext({$:id=>nodes[id],Promise});vm.runInContext(code,c);return{nodes,confirm:c.confirmPaidAction};}
(async()=>{let checks=0;const ok=(v,m)=>{assert.ok(v,m);checks++;};
 const a=boot();const pending=a.confirm('Your own API account may be charged.');ok(a.nodes.paidConfirmDialog.open,'HTML modal opens');ok(a.nodes.paidConfirmNo.focused,'Cancel receives initial focus');ok(a.nodes.paidConfirmMessage.textContent.includes('may be charged'),'billing message is visible');ok(await a.confirm('duplicate')===false,'duplicate action cannot share acceptance');a.nodes.paidConfirmYes.onclick();ok(await pending===true&&!a.nodes.paidConfirmDialog.open,'explicit Enable resolves true and closes');
 const b=boot();const cancelled=b.confirm('Enable?');b.nodes.paidConfirmNo.onclick();ok(await cancelled===false,'Cancel never enables paid use');
 const c=boot();let prevented=false;const escape=c.confirm('Enable?');c.nodes.paidConfirmDialog.oncancel({preventDefault:()=>prevented=true});ok(await escape===false&&prevented,'Escape cancels safely');
 const d=boot();const test=d.confirm('This test may charge your account.',{title:'Test paid API connections?',confirmLabel:'Run paid test'});ok(d.nodes.paidConfirmTitle.textContent==='Test paid API connections?'&&d.nodes.paidConfirmYes.textContent==='Run paid test','same dialog labels connection tests precisely');d.nodes.paidConfirmDialog.close();ok(await test===false,'closing modal without approval cancels');
 ok(!/window\.confirm/.test(app),'paid setup does not invoke a blocking browser confirmation');
 console.log(checks+' paid confirmation dialog tests passed (no API calls)');
})().catch(e=>{console.error(e);process.exitCode=1;});
