'use strict';const fs=require('fs'),vm=require('vm'),assert=require('assert'),path=require('path');const root=path.resolve(__dirname,'../docs');const bank=JSON.parse(fs.readFileSync(root+'/bank.json'));const html=fs.readFileSync(root+'/index.html','utf8');let tests=0;async function test(n,f){try{await f();tests++;}catch(e){console.error('FAIL',n);throw e}}
class El{constructor(tag,doc){this.tagName=tag;this.doc=doc;this.children=[];this.childNodes=this.children;this.dataset={};this.className='';this.hidden=false;this.style={setProperty(){}};this.classList={add(){},remove(){},toggle(){}};this.offsetTop=0;this.clientHeight=500;this.scrollTop=0;}set id(v){this._id=v;this.doc.ids[v]=this}get id(){return this._id}append(...x){this.children.push(...x)}set innerHTML(v){this._html=v;this.children.length=0}get innerHTML(){return this._html||''}setAttribute(k,v){this[k]=v}querySelectorAll(){return[]}querySelector(){return new El('input',this.doc)}scrollIntoView(){}scrollTo(){}addEventListener(){}removeEventListener(){}play(){return Promise.resolve()}pause(){}}
function doc(){const d={ids:{},createElement(t){return new El(t,d)},getElementById(id){return d.ids[id]||null},querySelectorAll(){return[]},querySelector(){return new El('div',d)},addEventListener(){},removeEventListener(){},visibilityState:'visible'};for(const match of html.matchAll(/id="([^"]+)"/g)){const el=new El('div',d);el.id=match[1];el.hidden=match[1]!=='home';}return d}
function storage(seed={}){const map=new Map(Object.entries(seed).map(([k,v])=>[k,typeof v==='string'?v:JSON.stringify(v)]));return{getItem:k=>map.get(k)||null,setItem:(k,v)=>map.set(k,v),map}}
async function boot({offline=false,cache=true,noBridge=false,progress=null,events=null,savedSettings=null,nativeOk=true}={}){const local=storage({...cache?{'pp.bank':bank}:{},...progress?{'pp.progress':progress}:{},...savedSettings?{'pp.settings':savedSettings}:{}}),d=doc(),timeouts=new Map();let tid=0,requests=[];const c={console,Date,Promise,Map,Set,JSON,Object,Number,String,Array,Math,Error,RegExp,URLSearchParams,TextEncoder,TextDecoder,AbortController,structuredClone,Buffer,performance:{now:()=>0},localStorage:local,document:d,window:null,navigator:{mediaDevices:{addEventListener(){}},locks:{request:(k,f)=>f()},serviceWorker:{register:async()=>{}},clipboard:{writeText:async()=>{}}},location:{search:'',origin:'http://localhost'},matchMedia:()=>({matches:false}),setTimeout:(f,ms)=>{timeouts.set(++tid,f);return tid},clearTimeout:id=>timeouts.delete(id),setInterval:(f,ms)=>++tid,clearInterval(){},addEventListener(){},removeEventListener(){},fetch:async(url,opts)=>{requests.push({url,opts});if(offline)throw Error('offline');if(String(url)==='bank.json')return{ok:true,json:async()=>bank};throw Error('Unexpected network request '+url)},Voice:{init(){},unlock(){},onChange(){},st:{neural:'ready'},say:async()=>{},stop(){},lastPos:0},Ear:{st:{nativeOk},localLoads:0,initLocal(){this.localLoads++},onChange(){},stop(){},release(){},available:false},MediaMetadata:function(){},Parse:{},Help:{explain:async()=>{},expand:async()=>{}},Tutorbot:{converse:async()=>{}},CHAIN:[],PROVIDERS:{}};c.window=c;c.scrollTo=()=>{};vm.createContext(c);
for(const f of ['ai.js','murmur-sync.js','murmur-adaptive.js',...noBridge?[]:['phone-study.js'],'app.js']){vm.runInContext(fs.readFileSync(root+'/'+f,'utf8').replace('(async function main() {','globalThis.bootPromise = (async function main() {'),c,{filename:f});if(f==='ai.js')vm.runInContext('Help.explain=async()=>{}; Help.expand=async()=>{}; Tutorbot.converse=async()=>{};',c);}
vm.runInContext('globalThis.Test = { Tutor, Session, Lecture, settings, progress, get Study(){return Study;}, renderHome, Sync, UI };',c);await c.bootPromise;return{c,d,local,requests,timeouts}}
(async()=>{
await test('all JavaScript references exist and parse',()=>{for(const [,f]of html.matchAll(/<script src="([^"]+)"/g)){assert(fs.existsSync(root+'/'+f));new vm.Script(fs.readFileSync(root+'/'+f,'utf8'))}});
await test('online cold start uses bank and renders plans',async()=>{const b=await boot({cache:false});assert.equal(b.d.getElementById('btnStart').disabled,false);assert(b.d.getElementById('adaptivePlan').children.length>0);assert(b.c.Test.Study);assert(!b.requests.some(r=>String(r.url).includes('api.github.com')));await b.c.Test.Study.destroy()});
await test('warm offline start preserves legacy history and bookmarks',async()=>{const p={items:{[bank.items[0].id]:{n:5,ok:3,bad:2,last:10,streak:1,due:100}},lectures:{bookmark:{seg:4,last:100}},lessons:{},topics:{},sessions:[],updated:100};const b=await boot({offline:true,progress:p});assert.equal(b.c.Test.progress.items[bank.items[0].id].n,5);assert.equal(b.c.Test.progress.lectures.bookmark.seg,4);assert.equal(b.c.Test.Study.profile().totals.independentAttempts,0);assert.equal(b.d.getElementById('btnStart').disabled,false);await b.c.Test.Study.destroy()});
await test('large legacy import preserves all counters without inventing independent events',async()=>{const items={};for(let i=0;i<500;i++)items['legacy'+i]={n:10,ok:7,bad:3,last:1000+i,streak:1,due:90000+i};const b=await boot({offline:true,progress:{items,lessons:{},lectures:{},topics:{},sessions:[]}}),T=b.c.Test;assert.equal(T.Study.client.records('phone.items').length,500);for(let i=0;i<500;i++){const saved=T.Study.client.getRecord('phone.items','legacy'+i);assert.equal(saved.n,10);assert.equal(saved.ok,7);assert.equal(T.progress.items['legacy'+i].bad,3);}assert.equal(T.Study.profile().totals.independentAttempts,0);await T.Study.destroy()});
await test('cold offline with no cache has helpful bank message',async()=>{const b=await boot({offline:true,cache:false});assert.match(b.d.getElementById('bankInfo').textContent,/Open the app once while online/);assert.equal(b.c.Test.Study,null)});
await test('missing bridge cannot disable existing voice app',async()=>{const b=await boot({noBridge:true});assert.equal(b.d.getElementById('btnStart').disabled,false);assert.match(b.d.getElementById('sharedSyncStatus').textContent,/voice lessons/)});
await test('independent, hint, taught, retry and reveal paths retain evidence',async()=>{const b=await boot(),T=b.c.Test,got=[];T.Study.record=(i,e)=>{got.push(e);return Promise.resolve()};vm.runInContext('speak=async()=>true; UI.mark=()=>{}; UI.options=()=>{}; Session.running=true; Tutor.afterWrong=async()=>"wrong";',b.c);let sample=bank.items.find(i=>i.type==='tf');
 async function ask(seq,retry=false,context={}){b.c.queue=seq;vm.runInContext('hear=async()=>queue.shift()',b.c);return T.Tutor.ask(sample,retry,context)}
 await ask([{cmd:{tf:sample.answer}}]);assert.equal(got.at(-1).assisted,false);
 await ask([{cmd:'hint'},{cmd:{tf:sample.answer}}]);assert.equal(got.at(-1).assisted,true);
 await ask([{cmd:{tf:sample.answer}}],false,{taught:true});assert.equal(got.at(-1).assisted,true);
 await ask([{cmd:{tf:sample.answer}}],true);assert.equal(got.at(-1).assisted,true);
 await ask([{cmd:{reveal:true}}]);assert.equal(got.at(-1).revealed,true);assert.equal(got.at(-1).assisted,true);
 const count=got.length;await ask([{cmd:'skip'}]);assert.equal(got.length,count);
 await ask([{cmd:'explain'},{cmd:{tf:sample.answer}}]);assert.equal(got.at(-1).assisted,true);
 assert.equal(T.progress.items[sample.id].streak,0);await T.Study.destroy()});
await test('help is durable even when the question is abandoned',async()=>{const b=await boot(),T=b.c.Test,sample=bank.items.find(i=>i.type==='tf');vm.runInContext('speak=async()=>true; UI.mark=()=>{}; UI.options=()=>{}; Session.running=true;',b.c);b.c.queue=[{cmd:'hint'},{cmd:'hint'},{cmd:'skip'}];vm.runInContext('hear=async()=>queue.shift()',b.c);await T.Tutor.ask(sample);const events=T.Study.events();assert.equal(events.length,1);assert.equal(events[0].status,'guided');assert.equal(T.Study.profile().totals.independentAttempts,0);assert.equal(T.Session.asked,0);const saved=JSON.parse(b.local.getItem('murmur.sync.v3.murmur-phone'));assert.equal(Object.keys(saved.doc.events).length,1);await T.Study.record(sample,{correct:true,assisted:false});assert.equal(T.Study.profile().totals.independentAttempts,0);await T.Study.destroy()});
await test('taught question retains support when skipped without consuming first hint',async()=>{const b=await boot(),T=b.c.Test,sample=bank.items.find(i=>i.type==='tf');vm.runInContext('speak=async()=>true; UI.mark=()=>{}; UI.options=()=>{}; Session.running=true;',b.c);b.c.queue=[{cmd:'dontknow'},{cmd:'skip'}];vm.runInContext('hear=async()=>queue.shift()',b.c);assert.equal(await T.Tutor.ask(sample,false,{taught:true}),'skip');assert.equal(T.Study.events().length,1);assert.equal(T.Study.events()[0].status,'guided');assert.equal(T.Session.asked,0);await T.Study.destroy()});
await test('wrong answer retains independent error and records shown feedback',async()=>{const b=await boot(),T=b.c.Test,sample=bank.items.find(i=>i.type==='tf');vm.runInContext('speak=async()=>true; UI.mark=()=>{}; UI.options=()=>{}; Session.running=true; Tutor.afterWrong=async()=>"wrong";',b.c);b.c.queue=[{cmd:{tf:!sample.answer}}];vm.runInContext('hear=async()=>queue.shift()',b.c);await T.Tutor.ask(sample);const events=T.Study.events();assert.equal(events.length,2);assert(events.some(e=>e.independent&&e.status==='missed'));assert(events.some(e=>e.revealed&&e.mode==='answer-feedback'));assert.equal(T.Study.profile().totals.independentAttempts,1);assert.equal(T.Study.profile().totals.independentCorrect,0);assert.equal(T.Session.asked,1);await T.Study.destroy()});
await test('new independent success schedules one day, not three',async()=>{const b=await boot(),T=b.c.Test;T.Session.running=true;T.Study.record=()=>{};let i=bank.items[0],now=Date.now();await T.Tutor.record(i,true,false,{});assert(T.progress.items[i.id].due>=now+86400000&&T.progress.items[i.id].due<now+86401000);await T.Study.destroy()});
await test('first launch without browser recognition waits for download consent',async()=>{const b=await boot({nativeOk:false});assert.equal(b.c.Ear.localLoads,0);await b.c.Test.Study.destroy();const returning=await boot({nativeOk:false,savedSettings:{localStt:true}});assert.equal(returning.c.Ear.localLoads,0);await returning.c.Test.Study.destroy()});
await test('new credentials never inherit the public legacy repository',async()=>{const b=await boot(),T=b.c.Test;T.settings.ghRepo='owner/public';T.settings.ghToken='legacy-secret';await T.Study.sync();assert(!b.requests.some(r=>String(r.url).includes('api.github.com')));const exported=T.Study.exportData();assert(!JSON.stringify(exported).includes('legacy-secret'));await T.Study.destroy()});
await test('phone reset does not fabricate mastery and filters old cloud copies',async()=>{const b=await boot(),T=b.c.Test;let i=bank.items[0];T.progress.items[i.id]={last:10,n:3,ok:3};await T.Study.capture();await T.Study.resetPhoneHistory();assert(!T.progress.items[i.id]);await T.Study.capture();assert.equal(T.Study.profile().totals.independentAttempts,0);await T.Study.destroy()});
await test('newer remote lesson completion replaces an older local completion',async()=>{const b=await boot(),T=b.c.Test;T.progress.lessons.example={done:10,wrongs:3};T.Sync.merge({items:{},lessons:{example:{done:20,wrongs:0}}});assert.equal(T.progress.lessons.example.done,20);assert.equal(T.progress.lessons.example.wrongs,0);T.Sync.merge({items:{},lessons:{example:{done:15,wrongs:2}}});assert.equal(T.progress.lessons.example.done,20);assert.equal(T.Study.profile().totals.independentAttempts,0);await T.Study.destroy()});
await test('navigation and push use one adapter sync without redundant capture',async()=>{const b=await boot(),T=b.c.Test;let calls=0;T.Study.capture=()=>{throw Error('redundant capture')};T.Study.sync=async()=>{calls++};T.Sync.pushSoon();T.UI.show('home');assert.equal(calls,2);await T.Study.destroy()});
await test('legacy API is read only; new push delegates shared private client',()=>{const s=fs.readFileSync(root+'/app.js','utf8'),sync=s.slice(s.indexOf('const Sync = {'),s.indexOf('// ------------------------------------------------------------------ UI'));assert(!sync.includes("method: 'PUT'"));assert(sync.includes('Study.sync()'))});
await test('service worker cache includes all new modules and offline fallback',async()=>{const sw=fs.readFileSync(root+'/sw.js','utf8');const shell=sw.match(/const SHELL = '([^']+)'/)[1];assert(Number(shell.split('-v')[1])>=14);for(let f of ['murmur-sync.js','murmur-adaptive.js','phone-study.js'])assert(sw.includes(f));let handlers={},cache=new Map,all=[],mode='online';let scope={location:{origin:'http://localhost'},URL,self:{addEventListener:(n,f)=>handlers[n]=f,skipWaiting:async()=>{},clients:{claim:async()=>{}}},caches:{open:async()=>({addAll:async names=>{for(let name of names){assert(fs.existsSync(path.join(root,name)));cache.set('http://localhost/'+name.replace(/^\.\//,''),{ok:true,cached:true,url:name})}all=names},put:async(req,val)=>cache.set(typeof req==='string'?req:req.url,val)}),keys:async()=>['pp-shell-v12',shell],delete:async()=>{},match:async req=>cache.get(typeof req==='string'?req:req.url)},fetch:async req=>{if(mode==='offline')throw Error('offline');return{ok:mode!=='error',clone(){return this},url:req.url}}};vm.createContext(scope);vm.runInContext(sw,scope);let job;handlers.install({waitUntil:p=>job=p});await job;assert(all.length>10);mode='offline';let result;handlers.fetch({request:{url:'http://localhost/murmur-adaptive.js',method:'GET'},respondWith:p=>result=p});assert((await result).cached);mode='error';handlers.fetch({request:{url:'http://localhost/murmur-adaptive.js',method:'GET'},respondWith:p=>result=p,waitUntil:()=>{}});assert((await result).cached);assert(cache.get('http://localhost/murmur-adaptive.js').cached);handlers.fetch({request:{url:'https://api.github.com/repos/x/y',method:'GET'},respondWith:()=>{throw Error('External API must not be cached')}})});
console.log(tests+' phone integration/bootstrap/offline tests passed');
})().catch(e=>{console.error(e);process.exitCode=1});
