'use strict';
const assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm');
let checks=0;const ok=(v,m)=>{assert.ok(v,m);checks++;};
function harness(){let now=Date.parse('2026-10-03T12:00:00Z'),serial=0;const timers=new Map(),listeners={},docListeners={};const DateMock=class extends Date{constructor(...args){super(...(args.length?args:[now]));}static now(){return now;}};const add=(map)=>(n,f)=>(map[n]??=[]).push(f),remove=(map)=>(n,f)=>map[n]=(map[n]||[]).filter(x=>x!==f);const env={module:{exports:{}},Buffer,TextEncoder,TextDecoder,Date:DateMock,Math,JSON,Promise,AbortController,console,setTimeout:(f,ms)=>{const id=++serial;timers.set(id,{f,ms});return id;},clearTimeout:id=>timers.delete(id),setInterval:(f,ms)=>{const id=++serial;timers.set(id,{f,ms,interval:true});return id;},clearInterval:id=>timers.delete(id),navigator:{onLine:true},document:{visibilityState:'visible',addEventListener:add(docListeners),removeEventListener:remove(docListeners)},addEventListener:add(listeners),removeEventListener:remove(listeners)};vm.runInNewContext(fs.readFileSync(require.resolve('../docs/murmur-sync.js'),'utf8'),env);return {M:env.module.exports,env,timers,now:()=>now,advance:ms=>now+=ms,event:(n)=>{for(const f of listeners[n]||[])f({});},visibility:hidden=>{env.document.visibilityState=hidden?'hidden':'visible';for(const f of docListeners.visibilitychange||[])f({});}};}
const storage=()=>{let value=null;return {read:()=>value,write:x=>value=x,raw:()=>value};};
const res=(status,data={},headers={})=>({status,ok:status>=200&&status<300,json:async()=>data,headers:{get:n=>headers[n.toLowerCase()]??null}});
const attempt=(id)=>({id,questionId:id,course:'DIGI210',topic:'Gates',credit:1,independent:true});
function server(M){let doc={schema:3,events:{},records:{}},sha=1,calls=[],puts=0;const fetch=async(url,init={})=>{calls.push({url,method:init.method||'GET'});if(!url.includes('/contents/'))return res(200,{private:true});if(init.method!=='PUT')return res(200,{sha:String(sha),content:M.encode(JSON.stringify(doc))});const body=JSON.parse(init.body);if(body.sha!==String(sha))return res(409);puts++;doc=JSON.parse(M.decode(body.content));sha++;return res(200);};return {fetch,calls,get puts(){return puts;},get doc(){return doc;}};}
const settle=async()=>{for(let i=0;i<60;i++)await Promise.resolve();};
(async()=>{
 {const h=harness(),s=server(h.M),c=h.M.create({storage:storage(),fetch:s.fetch,config:{repo:'a/private',token:'test'}});await c.ready;await c.recordAttempt(attempt('first'));await Promise.all(Array.from({length:30},()=>c.sync()));ok(s.calls.length===3,'30 concurrent calls share one transaction');ok(s.puts===1,'one coalesced write');await c.sync();ok(s.calls.length===3,'immediate idle call is suppressed');h.advance(60000);await c.sync();ok(s.calls.length===3,'idle one-minute poll suppressed');h.advance(240000);await c.sync();ok(s.calls.length===5,'idle fetch resumes at five minutes');await c.recordAttempts(Array.from({length:100},(_,i)=>attempt('answer'+i)));await c.sync();ok(s.calls.length===5,'new answers do not bypass active cooldown');h.advance(59999);await c.sync();ok(s.calls.length===5,'active cooldown lasts the full minute');h.advance(1);await c.sync();ok(s.calls.length===8&&Object.keys(s.doc.events).length===101,'all queued answers upload together after one minute');await c.destroy();}
 {const h=harness(),s=server(h.M),c=h.M.create({storage:storage(),fetch:s.fetch,config:{repo:'a/private',token:'test'}});await c.ready;c.start();h.visibility(true);await c.recordAttempt(attempt('hidden'));await c.sync();for(const t of h.timers.values())if(t.interval)t.f();await settle();ok(s.calls.length===0,'hidden writes/polls remain local');ok(h.timers.size===1,'hidden state has only the guarded interval');h.visibility(false);for(let i=0;i<30;i++)h.event('focus');await settle();ok(s.calls.length===3,'visibility/focus burst runs one sync');h.env.navigator.onLine=false;h.advance(60000);await c.recordAttempt(attempt('offline'));await c.sync();ok(s.calls.length===3,'known offline state sends no requests');h.env.navigator.onLine=true;for(let i=0;i<20;i++)h.event('online');await settle();ok(s.calls.length===6&&s.puts===2,'reconnect burst uploads once');h.event('pagehide');await settle();ok(s.calls.length===6,'pagehide flushes local data without extra network');await c.destroy();}
 {const h=harness(),disk=storage();let calls=0;const config={repo:'a/private',token:'test'},fetch=async()=>{calls++;return res(429,{}, {'retry-after':'120'});};const c=h.M.create({storage:disk,fetch,config});await c.ready;await c.recordAttempt(attempt('rate'));await assert.rejects(()=>c.sync(),/rate limit/);checks++;for(let i=0;i<20;i++)await c.sync();ok(calls===1,'429 repeated triggers honor Retry-After');ok(c.pending&&c.events().length===1,'rate limit preserves pending answer');await c.destroy();const d=h.M.create({storage:disk,fetch,config});await d.ready;h.advance(119999);await d.sync();ok(calls===1,'reload preserves rate cooldown');h.advance(1);await assert.rejects(()=>d.sync(),/rate limit/);checks++;ok(calls===2,'retry resumes only after server wait');h.advance(119999);await d.sync();ok(calls===2,'second failure uses exponential backoff');await d.destroy();}
 {const h=harness();let calls=0;const future=new Date(h.now()+180000).toUTCString(),c=h.M.create({storage:storage(),fetch:async()=>{calls++;return res(429,{}, {'retry-after':future});},config:{repo:'a/private',token:'test'}});await c.ready;await assert.rejects(()=>c.sync());checks++;h.advance(179999);await c.sync();ok(calls===1,'Retry-After HTTP date honored');await c.destroy();}
 {const h=harness();let calls=0;const reset=(h.now()+3600000)/1000,c=h.M.create({storage:storage(),fetch:async()=>{calls++;return res(403,{}, {'x-ratelimit-remaining':'0','x-ratelimit-reset':String(reset),'retry-after':'60'});},config:{repo:'a/private',token:'test'}});await c.ready;await assert.rejects(()=>c.sync());checks++;h.advance(3600000);await c.sync();ok(calls===1,'primary reset overrides shorter Retry-After with clock margin');h.advance(1000);await assert.rejects(()=>c.sync());checks++;ok(calls===2,'primary quota resumes after reset');await c.destroy();}
 {const h=harness();let calls=0;const c=h.M.create({storage:storage(),fetch:async()=>{calls++;return res(403,{message:'You have exceeded a secondary rate limit.'});},config:{repo:'a/private',token:'test'}});await c.ready;await assert.rejects(()=>c.sync(),/rate limit/);checks++;h.advance(59999);await c.sync();ok(calls===1,'secondary quota without headers waits at least one minute');h.advance(1);await assert.rejects(()=>c.sync());checks++;h.advance(60000);await c.sync();ok(calls===2,'secondary failures increase wait');await c.destroy();}
 {const h=harness();let calls=0;const c=h.M.create({storage:storage(),fetch:async()=>{calls++;return res(200,{private:true},{'x-ratelimit-remaining':'0','x-ratelimit-reset':String((h.now()+600000)/1000)});},config:{repo:'a/private',token:'test'}});await c.ready;await assert.rejects(()=>c.sync());checks++;ok(calls===1,'last allowed request prevents subsequent request in same transaction');await c.destroy();}
 {const h=harness(),s=server(h.M),config={repo:'a/private',token:'wrong'};let denied=0;const c=h.M.create({storage:storage(),fetch:async(...args)=>{if(config.token==='wrong'){denied++;return res(401);}return s.fetch(...args);},config:()=>config});await c.ready;await assert.rejects(()=>c.sync());checks++;h.advance(300000);await c.sync();ok(denied===1,'bad credentials do not poll every minute');config.token='correct';await c.sync();ok(s.calls.length===2,'corrected connection can recover immediately');await c.destroy();}
 {const h=harness(),s=server(h.M),clients=[];for(let i=0;i<3;i++){const c=h.M.create({storage:storage(),fetch:s.fetch,config:{repo:'a/private',token:'test'}});await c.ready;await c.recordAttempt(attempt('device'+i));await c.sync();clients.push(c);}ok(Object.keys(s.doc.events).length===3,'three devices preserve each independent event');for(let minute=1;minute<60;minute++){h.advance(60000);for(const [i,c]of clients.entries()){await c.recordAttempt(attempt(i+'-'+minute));for(let burst=0;burst<5;burst++)await c.sync();}}ok(s.calls.length===540,'three continuously active devices make 540 normal requests/hour');ok(s.puts===180,'three active devices create at most 180 normal commits/hour');ok(Object.keys(s.doc.events).length===180,'batched three-device history remains complete');for(const c of clients)await c.destroy();}
 {const h=harness(),s=server(h.M),clients=[];for(let i=0;i<3;i++){const c=h.M.create({storage:storage(),fetch:s.fetch,config:{repo:'a/private',token:'test'}});await c.ready;clients.push(c);}for(let minute=0;minute<60;minute++){if(minute)h.advance(60000);for(const c of clients)await c.sync();}ok(s.calls.length===72&&s.puts===0,'three visible idle devices use 72 normal reads/hour, zero commits');for(const c of clients)await c.destroy();}
 {const h=harness();let calls=0,puts=0;const c=h.M.create({storage:storage(),fetch:async(url,init={})=>{calls++;if(!url.includes('/contents/'))return res(200,{private:true});if(init.method==='PUT'){puts++;return res(409);}return res(404);},config:{repo:'a/private',token:'test'}});await c.ready;await c.recordAttempt(attempt('conflict'));let finished=false,error;const work=c.sync().catch(e=>error=e).finally(()=>finished=true);for(let i=0;i<10&&!finished;i++){await settle();for(const [id,t]of h.timers)if(t.ms===1000||t.ms===2000){h.timers.delete(id);t.f();}}await work;ok(error&&/Concurrent/.test(error.message),'repeated conflicts end with a bounded failure');ok(calls===7&&puts===3,'one transaction has at most three conflict writes');for(let i=0;i<20;i++)await c.sync();ok(calls===7,'conflicts cannot trigger an immediate retry storm');await c.destroy();}
 {const h=harness(),disk=storage();let calls=0;const c=h.M.create({storage:disk,fetch:async()=>{calls++;throw new Error('network down');},config:{repo:'a/private',token:'test'}});await c.ready;for(let i=0;i<8;i++){await assert.rejects(()=>c.sync());const n=JSON.parse(disk.raw()).network;ok(n.backoffUntil-h.now()===Math.min(3600000,60000*2**i),'network retry '+i+' increases up to one hour');h.advance(n.backoffUntil-h.now());}ok(calls===8,'network retry count stays bounded by backoff');await c.destroy();}
 console.log(checks+' quota tests passed');
})().catch(e=>{console.error(e);process.exitCode=1;});
