const assert=require('node:assert/strict');const {create,mount,CHOICE_KEY}=require('../docs/voice-setup.js');
let tests=0;const ok=(x,m)=>{assert.ok(x,m);tests++;};const tick=()=>new Promise(r=>setTimeout(r,0));
function engines(){let vc=0,ec=0;const calls=[];const v={neural:'off',progress:0,listeners:new Set(),cache:new Map(),engine:'system'},e={local:'off',localProgress:0,listeners:new Set()};const emit=s=>{for(const f of s.listeners)f(s);};
 const voice={st:v,onChange:f=>v.listeners.add(f),initNeural:async(force,options)=>{vc++;calls.push(['voice',options]);v.neural='loading';emit(v);},stop:()=>{},reset:()=>{v.neural='off';v.progress=0;emit(v);}},ear={st:e,onChange:f=>e.listeners.add(f),initLocal:async options=>{ec++;calls.push(['ear',options]);e.local='loading';emit(e);},stop:()=>{},reset:()=>{e.local='off';e.localProgress=0;emit(e);}};
 return {voice,ear,calls,voiceReady:()=>{v.neural='ready';emit(v);},earReady:()=>{e.local='ready';emit(e);},earFail:()=>{e.local='failed';e.lastError='Network interrupted';emit(e);},emitVoice:()=>emit(v),counts:()=>[vc,ec]};}
const storage=()=>{const data=new Map();return {getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,v),data};};
function fakeDOM(){const ids=['audioSetupDialog','audioPackStatus','audioDialogStatus','audioPackProgress','audioDialogProgress','audioVoiceStatus','audioDialogVoice','audioRecognizerStatus','audioDialogRecognizer','btnAudioPacks','btnRedownloadAudio','audioDownloadBoth','audioFindFiles','btnAudioExisting','audioRecovery','audioChooseFolder','audioChooseFiles','audioFolderInput','audioFilesInput','audioRecoveryStatus','audioModelHint'];const elements=Object.fromEntries(ids.map(id=>[id,{id,hidden:false,value:'',disabled:false,textContent:'',handlers:{},classList:{toggle:()=>{}},setAttribute(){},removeAttribute(){},addEventListener(n,f){this.handlers[n]=f;},showModal(){this.open=true;},close(){this.open=false;this.handlers.close?.();},click(){this.clicked=true;}}]));const main={inert:false};return {elements,main,document:{getElementById:id=>elements[id],querySelectorAll:()=>[main],documentElement:{classList:{toggle:()=>{}}}}};}
(async()=>{
 const a=engines(),st=storage(),settings={earMode:'auto',micId:'chosen-mic',mic:false};let saves=0;const c=create({...a,settings,save:()=>saves++,storage:st});
 st.setItem('murmur.audio.setup.v1',JSON.stringify({choice:'later'}));ok(!c.seen()&&a.counts().join()==='0,0','old defer ignored and no unconfirmed download');c.remember('later');ok(!c.seen(),'later cannot bypass required setup');
 const pending=c.download();ok(pending===c.download(),'double tap shares one download');ok(JSON.parse(st.getItem(CHOICE_KEY)).confirmed,'download confirmation saved');await tick();ok(a.counts().join()==='1,0','engines prepared sequentially');a.voice.st.progress=100;a.emitVoice();ok(!c.snapshot().ready&&c.snapshot().busy,'100 percent transfer is not readiness');a.voiceReady();await tick();ok(a.counts().join()==='1,1','recognizer starts after voice readiness');a.earFail();const failure=await pending;ok(!failure.ready&&failure.failed[0].message==='Network interrupted','partial failure not ready');ok(c.snapshot().error.includes('Network interrupted'),'failure visible');ok(settings.earMode==='auto','failed recognizer not applied');
 const retry=c.download();await tick();ok(a.counts().join()==='1,2','successful voice reused on retry');a.earReady();const result=await retry;ok(result.ready&&c.snapshot().ready,'both workers required');ok(settings.earMode==='local'&&settings.neuralVoice&&settings.localStt,'ready engines applied');ok(settings.micId==='chosen-mic'&&!settings.mic,'microphone preference retained');ok(saves>0,'preferences saved');
 const requests=[{url:'https://huggingface.co/onnx-community/Kokoro-82M-v1.0-ONNX/resolve/main/onnx/model.onnx'},{url:'https://huggingface.co/onnx-community/whisper-base.en/resolve/main/onnx/encoder_model.onnx'},{url:'https://huggingface.co/onnx-community/whisper-base.en/resolve/main/onnx/decoder_model_merged_q4.onnx'},{url:'https://huggingface.co/unrelated/private-model/config.json'}],deleted=[];const cacheStore={keys:async()=>['transformers-cache','pp-shell-v13'],open:async key=>{assert.equal(key,'transformers-cache');return {keys:async()=>requests,delete:async r=>deleted.push(r.url)};}};
 const d=create({...engines(),settings:{},storage:storage(),caches:cacheStore});ok(await d.cached(),'both model weight groups detected');ok(await d.clearModels()===3&&deleted.length===3,'redownload clears only audio model files');ok(!deleted.some(u=>u.includes('private-model')),'unrelated cache retained');
 let voiceDeleted=0;const voiceCache=create({...engines(),settings:{},storage:storage(),caches:{keys:async()=>['kokoro-voices'],open:async()=>({keys:async()=>[{url:'https://huggingface.co/onnx-community/Kokoro-82M-v1.0-ONNX/resolve/main/voices/af_heart.bin'}],delete:async()=>voiceDeleted++})}});ok(await voiceCache.clearModels()===1&&voiceDeleted===1,'redownload includes separate Kokoro voice-vector cache');
 const cold=engines(),coldCore=create({...cold,settings:{},storage:storage()});const restored=coldCore.restore();await tick();ok(cold.calls[0][1].cacheOnly===true,'restore requests cache-only voice');cold.voiceReady();await tick();ok(cold.calls[1][1].cacheOnly===true,'restore requests cache-only recognizer');cold.earReady();await restored;ok(!coldCore.seen(),'restore does not record consent for network download');
 const timeout=create({...engines(),settings:{},storage:storage(),timeoutMs:5});const timed=await timeout.download();ok(!timed.ready&&timed.failed.length===2&&!timeout.snapshot().busy,'stalled workers fail with retry enabled');
 const dom=fakeDOM(),m=mount({...engines(),document:dom.document,settings:{},storage:st,search:''});ok(dom.elements.audioSetupDialog.open&&dom.main.inert,'first launch blocks study despite old defer');ok(!m.isReady()&&!m.ensureReady(),'study guard returns false until ready');let prevented=false;dom.elements.audioSetupDialog.handlers.cancel({preventDefault:()=>prevented=true});ok(prevented,'Escape prevented');dom.elements.audioSetupDialog.close();ok(dom.elements.audioSetupDialog.open,'programmatic close cannot bypass required setup');dom.elements.audioFindFiles.onclick();ok(dom.elements.audioRecovery.open,'Find existing files available alongside download');dom.elements.audioChooseFolder.onclick();ok(dom.elements.audioFolderInput.clicked,'folder picker available');dom.elements.audioChooseFiles.onclick();ok(dom.elements.audioFilesInput.clicked,'mobile-compatible file picker available');
 const qa=fakeDOM(),qaMount=mount({...engines(),document:qa.document,settings:{},storage:storage(),search:'?qa'});ok(!qa.elements.audioSetupDialog.open&&qaMount.isReady()&&!qa.main.inert,'QA isolated bypass works');
 const cancelEngines=engines(),cancelCore=create({...cancelEngines,settings:{},storage:storage()});const cancelJob=cancelCore.download();cancelCore.cancel();await cancelJob;await tick();ok(cancelEngines.counts().join()==='0,0','internal cancellation prevents queued launch');
 const restoreDOM=fakeDOM(),restoreEngines=engines(),restoreCalls=[];restoreEngines.voice.initNeural=async(force,opts)=>{restoreCalls.push(opts);restoreEngines.voice.st.neural='failed';restoreEngines.voice.st.why='Missing cached model';restoreEngines.emitVoice();};restoreEngines.ear.initLocal=async opts=>{restoreCalls.push(opts);restoreEngines.earFail();};let imports=0;
 mount({...restoreEngines,document:restoreDOM.document,settings:{},storage:storage(),filesAPI:{importFiles:async()=>{imports++;return {imported:2,skipped:1,rejected:[{name:'model.bin',reason:'Checksum does not match.'}]};}}});restoreDOM.elements.audioFilesInput.files=[{name:'model.onnx'}];await restoreDOM.elements.audioFilesInput.onchange();
 ok(imports===1&&restoreCalls.every(x=>x.cacheOnly===true),'file recovery invokes cache-only verification without consent to download');ok(restoreDOM.main.inert&&restoreDOM.elements.audioRecoveryStatus.textContent.includes('2 files restored; 1 already saved; 1 unrelated'),'partial recovery stays locked and retains import counts');ok(restoreDOM.elements.audioDownloadBoth.textContent.includes('Download missing'),'missing files keep explicit download action');ok(restoreDOM.elements.audioRecoveryStatus.textContent.includes('model.bin: Checksum does not match.'),'file recovery preserves the rejected file name and reason');
 const incompatible=engines();incompatible.voice.initNeural=async()=>{incompatible.voice.st.neural='failed';incompatible.voice.st.why='nogpu';incompatible.emitVoice();};const blocked=await create({...incompatible,settings:{},storage:storage()}).download();ok(!blocked.ready&&incompatible.counts()[1]===0,'unsupported GPU does not waste bandwidth downloading an unusable required setup');
 console.log(tests+' required audio setup tests passed');
})().catch(e=>{console.error(e);process.exitCode=1;});
